// ─── lib/players.ts ──────────────────────────────────────────────────────────

import type { Player } from "@/lib/cardTypes";

export const WATCHLIST: Player[] = [
  {
    id:       "683002",
    name:     "Paul Skenes",
    team:     "Pittsburgh Pirates",
    position: "SP",
    cardName: "2024 Topps Chrome Rookie PSA 10",
    image:    "⚾",
    cardImage: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/683002/headshot/67/current",
    cardColor: "#FDB827",
    teamColor: "#27251F",
  },
  {
    id:       "682998",
    name:     "Jackson Holliday",
    team:     "Baltimore Orioles",
    position: "SS",
    cardName: "2024 Bowman Chrome Auto PSA 10",
    image:    "⚾",
    cardImage: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/682998/headshot/67/current",
    cardColor: "#DF4601",
    teamColor: "#000000",
  },
  {
    id:       "671939",
    name:     "Gunnar Henderson",
    team:     "Baltimore Orioles",
    position: "SS",
    cardName: "2023 Topps Chrome PSA 10",
    image:    "⚾",
    cardImage: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/671939/headshot/67/current",
    cardColor: "#DF4601",
    teamColor: "#000000",
  },
  {
    id:       "660670",
    name:     "Ronald Acuña Jr.",
    team:     "Atlanta Braves",
    position: "OF",
    cardName: "2018 Topps Update Rookie PSA 10",
    image:    "⚾",
    cardImage: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/660670/headshot/67/current",
    cardColor: "#CE1141",
    teamColor: "#13274F",
  },
  {
    id:       "808967",
    name:     "Wyatt Langford",
    team:     "Texas Rangers",
    position: "OF",
    cardName: "2024 Topps Chrome Rookie PSA 10",
    image:    "⚾",
    cardImage: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/808967/headshot/67/current",
    cardColor: "#003278",
    teamColor: "#C0111F",
  },
  {
    id:       "694973",
    name:     "Julio Rodriguez",
    team:     "Seattle Mariners",
    position: "OF",
    cardName: "2022 Topps Chrome Rookie PSA 10",
    image:    "⚾",
    cardImage: "https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/694973/headshot/67/current",
    cardColor: "#0C2C56",
    teamColor: "#005C5C",
  },
];
